### ISSUE TITLE
Which version of Bounce2?

### ISSUE THREAD

**Issue by terrag42** [jasoncoon/fastled-arcade#2]
I did a github search for Bounce2 library and there were several versions available. Did you use the Arduino IDE to install the library? I just want to be sure we are using the same library.

**Comment by jasoncoon** [comment]
I think I did use the Arduino library manager.  I think it's this one (the main one), but I'll confirm later: https://github.com/thomasfredericks/Bounce2

**Comment by terrag42** [comment]
Yes, this version of Bounce2 is in the Arduino Library manager and it worked for me.
