### ISSUE TITLE
Tips for reducing memory for global variables?

### ISSUE THREAD

**Issue by terrag42** [jasoncoon/fastled-arcade#3]
I am trying to compile this for an Arduino Uno or Nano, but the global variables use 198% of dynamic memory. Is there a particular global variable-rich game or mode that I can eliminate?

**Comment by jasoncoon** [comment]
I'd start with launcher which can handle 100 "balls".  Not sure how many bytes each, but probably at least 20: 100 x 20 == 2K

Try reducing ballCount, since there's no way 100 of them would be visible at once, even if you hit the buttons extremely quickly.

**Comment by terrag42** [comment]
Awesome, if I change ballCount from 100 to 17, I'm now using 99% of my global variables. I may change it to 10 balls so there is some room for local variables. Thanks!

**Comment by jasoncoon** [comment]
Great, no problem!  I'm sure there are plenty of other optimizations that can be made.  I used a Teensy which has plenty of room.  :)
